from .default import (referseg_transform_train,
                      vqa_transform_train,
                      densecap_transform_train,
                      referseg_transform_eval,
                      vqa_transform_eval,
                      densecap_transform_eval,
                      referseg_transform_train_posealign,
                      vqa_transform_train_posealign,
                      densecap_transform_train_posealign,
                      referseg_transform_eval_posealign,
                      vqa_transform_eval_posealign,
                      densecap_transform_eval_posealign,
                      referseg_transform_train_collectPose,
                      vqa_transform_train_collectPose,
                      densecap_transform_train_collectPose,
                      referseg_transform_eval_collectPose,
                      vqa_transform_eval_collectPose,
                      densecap_transform_eval_collectPose,
                      referseg_transform_train_posealign_collectpose,
                      vqa_transform_train_posealign_collectpose,
                      densecap_transform_train_posealign_collectpose,
                      referseg_transform_eval_posealign_collectpose,
                      vqa_transform_eval_posealign_collectpose,
                      densecap_transform_eval_posealign_collectpose,
                      )
from .transform import Compose
